vim.g.mapleader = " "

vim.keymap.set({ "i" }, "kj", "<Esc>", { silent = true })
vim.keymap.set({ "n" }, "Z", "<cmd>wa<CR><cmd>q<CR>", { silent = true })
vim.keymap.set({ "v" }, "Z", "<Esc>", { silent = true })

vim.keymap.set("n", "j", [[v:count?"j":"gj"]], { noremap = true, expr = true })
vim.keymap.set("n", "k", [[v:count?"k":"gk"]], { noremap = true, expr = true })

vim.keymap.set({ "v", "n", "i", "t" }, "<C-h>", [[<C-w>h]])
vim.keymap.set({ "v", "n", "i", "t" }, "<C-j>", [[<C-w>j]])
vim.keymap.set({ "v", "n", "i", "t" }, "<C-k>", [[<C-w>k]])
vim.keymap.set({ "v", "n", "i", "t" }, "<C-l>", [[<C-w>l]])
vim.keymap.set({ "v", "n", "i", "t" }, "<M-h>", [[<C-w>H]])
vim.keymap.set({ "v", "n", "i", "t" }, "<M-j>", [[<C-w>J]])
vim.keymap.set({ "v", "n", "i", "t" }, "<M-k>", [[<C-w>K]])
vim.keymap.set({ "v", "n", "i", "t" }, "<M-l>", [[<C-w>L]])
vim.keymap.set({ "v", "n", "i", "t" }, "<M-w>", [[<C-w>w]])
vim.keymap.set({ "v", "n", "i", "t" }, "<M-r>", [[<C-w>r]])
vim.keymap.set({ "v", "n", "i", "t" }, "<M-x>", [[<C-w>x]])
vim.keymap.set({ "v", "n", "i", "t" }, "<M-s>", [[<C-w>s]])
vim.keymap.set({ "v", "n", "i", "t" }, "<M-v>", [[<C-w>v]])
vim.keymap.set({ "v", "n", "i", "t" }, "<M-=>", [[<C-w>+]])
vim.keymap.set({ "v", "n", "i", "t" }, "<M-->", [[<C-w>-]])
vim.keymap.set({ "v", "n", "i", "t" }, "<M-,>", [[<C-w><Lt>]])
vim.keymap.set({ "v", "n", "i", "t" }, "<M-.>", [[<C-w>>]])
vim.keymap.set({ "v", "n", "i", "t" }, "<C-q>", [[<C-w>q]])
vim.keymap.set({ "v", "n", "i", "t" }, "<M-q>", [[<C-w>q]])
vim.keymap.set({ "n" }, "<Esc>", [[<Cmd>nohls<CR><Esc>]])
vim.keymap.set({ "t" }, "<Esc>", [[<C-\><C-n>]])
